CREATE DATABASE TUESDAY_GEN_QUIZ_DB;
GO

USE TUESDAY_GEN_QUIZ_DB;
GO

CREATE TABLE Supplier (
    suppID INT PRIMARY KEY IDENTITY(1,1),
    suppName NVARCHAR(100) NOT NULL,
    country NVARCHAR(50) NOT NULL,
    suppEmail NVARCHAR(100)
);
GO

CREATE TABLE Product (
    prodID INT PRIMARY KEY IDENTITY(1,1),
    prodName NVARCHAR(100) NOT NULL,
    supplier INT NOT NULL,
    quantity INT NOT NULL CHECK (quantity >= 0),
    price DECIMAL(18,2) NOT NULL,
    registeredDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (supplier) REFERENCES Supplier(suppID)
);
GO

CREATE TABLE Sales (
    salID INT PRIMARY KEY IDENTITY(1,1),
    product INT NOT NULL,
    saleDate DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (product) REFERENCES Product(prodID)
);
GO
